# Generated by Django 3.0.8 on 2020-07-21 14:58

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CachorroEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('condicao', multiselectfield.db.fields.MultiSelectField(choices=[('alergia', 'Alegia'), ('cardiaco', 'Cardiaco'), ('diabetes', 'Diabetes'), ('renal', 'Renal'), ('obesidade', 'Obesidade'), ('intestinal', 'Instestinal'), ('outro', 'Outro')], max_length=200, verbose_name='Qual o problema de saúde?')),
                ('medicamento', models.BooleanField(default=False, verbose_name='Ele toma algum medicamento?')),
                ('descricao', models.TextField(help_text='Escreva aqui', verbose_name='Breve descrição sobre o problema')),
                ('anexo', models.FileField(help_text='Clique ou arraste os arquivos nessa área para anexá-los', upload_to='uploads/anexos/%Y/%m/', verbose_name='Algum exame ou receita?')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('idEntrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Entrega')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Planos')),
                ('refDog', models.ManyToManyField(to='app.Cachorro')),
            ],
        ),
        migrations.AddField(
            model_name='cachorro',
            name='dogEspecial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.CachorroEspecial'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
    ]
