# Generated by Django 3.0.8 on 2020-07-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.BigIntegerField(default='', verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=150, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complemento (opcional)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default='', verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='', max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.BigIntegerField(default='', verbose_name='Telefone'),
        ),
    ]
