# Generated by Django 3.0.8 on 2020-07-22 01:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='atividade',
            field=models.CharField(choices=[('Caminhadas Diárias', 'Caminhadas Diárias'), ('Super Ativo', 'Super Ativo'), ('Nivel Olímpico', 'Nivel Olímpico')], default='', max_length=100, verbose_name='Nivel de atividade Diária'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='calculodia',
            field=models.IntegerField(default=0, verbose_name='Quantidade de ração diária para o cão (g/dia)'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='calculomes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de ração a receber (kg/mês)'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='castrado',
            field=models.BooleanField(choices=[(0, 'Não'), (1, 'Sim')], default=0, max_length=50, verbose_name='Ele é castrado?'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='fisico',
            field=models.CharField(choices=[('Magro', 'Magro'), ('Na Medida', 'Na Medida'), ('Gordinho', 'Gordinho'), ('Obeso', 'Obeso')], default='', help_text='Não sabe o estado físico do seu cão? Não tem problema, clique aqui e descubra.', max_length=100, verbose_name='Físico do cão'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento - Apenas mês e ano'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(default='', help_text='Digite aqui o nome (sobrenome opcional)', max_length=150, verbose_name='Nome do seu Dog'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='peso',
            field=models.IntegerField(default=0, help_text='Observação: Não sabe o peso exato? Não faz mal, você pode inserir um peso próximo.', verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='pesoideal',
            field=models.IntegerField(default=0, help_text='Segundo o conselho veterinario, caso seu cão tenha até 12 meses é obrigatorio você informar o peso ideal dele quando adulto. Fique tranquilo, você pode informar o peso aproximado.', verbose_name='Peso Ideal'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='raca',
            field=models.CharField(default='', help_text='Digite aqui...', max_length=100, verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea'), ('Indefinido', 'Indefinido')], default='', max_length=50, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.BigIntegerField(default=0, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=150, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complemento (opcional)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='', max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.BigIntegerField(default=0, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='dia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='', max_length=48, verbose_name='Quais dias da semana você pode receber a Ração Do Futuro?'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='frequencia',
            field=models.IntegerField(choices=[(1, ' 1 Entrega no mês (Grátis)'), (2, '2 Entregas no mês (R$9,90)')], default=0, verbose_name='Com qual frequência quer receber a Ração do Futuro?'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='periodo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], default='', max_length=27, verbose_name='Qual o período ideal para ser realizada a entrega?'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='preferencia',
            field=models.CharField(choices=[('Em mãos', 'Sempre em mãos'), ('Portaria', 'Pode deixar na portaria.')], default='', max_length=150, verbose_name='Para quem podemos entregar?'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='linkpagseguro',
            field=models.URLField(default='', verbose_name='URL do Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(default='', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sabores',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Carne de panela', 'Carne de panela'), ('Frango Xadrez', 'Frango Xadrez'), ('Risoto Suíno', 'Risoto Suíno')], default='', max_length=42, verbose_name='Escolha os sabores do futuro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pedido em aberto', 'Pedido em aberto'), ('Pedido finalizado pelo cliente', 'Pedido finalizado pelo cliente'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Pedido em preparo', 'Pedido em preparo'), ('Pedido em trânsito', 'Pedido em trânsito'), ('Pedido concluído', 'Pedido concluído')], default='', max_length=100, verbose_name='Status do pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor do pedido'),
        ),
        migrations.AddField(
            model_name='planos',
            name='condicaofrete',
            field=models.CharField(default='', max_length=50, verbose_name='Como será o frete? (Ex:"Frete R$9,90")'),
        ),
        migrations.AddField(
            model_name='planos',
            name='descricao',
            field=models.CharField(default='', max_length=300, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='planos',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome do Plano'),
        ),
        migrations.AddField(
            model_name='planos',
            name='refeicoes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de refeições'),
        ),
        migrations.AddField(
            model_name='planos',
            name='subdescricao',
            field=models.CharField(default='', max_length=300, verbose_name='Sub-descrição'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='descricao',
            field=models.TextField(default='', help_text='Escreva aqui', verbose_name='Breve descrição sobre o problema'),
        ),
    ]
