# Generated by Django 3.0.8 on 2020-07-22 00:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200721_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='dia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='', max_length=48, verbose_name='Quais dias da semana você pode receber a Ração Do Futuro?'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='frequencia',
            field=models.IntegerField(choices=[(1, ' 1 Entrega no mês (Grátis)'), (2, '2 Entregas no mês (R$9,90)')], default=0, verbose_name='Com qual frequência quer receber a Ração do Futuro?'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='periodo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], default='', max_length=27, verbose_name='Qual o período ideal para ser realizada a entrega?'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='preferencia',
            field=models.CharField(choices=[('Em mãos', 'Sempre em mãos'), ('Portaria', 'Pode deixar na portaria.')], default='', max_length=150, verbose_name='Para quem podemos entregar?'),
        ),
        migrations.AddField(
            model_name='planos',
            name='condicaofrete',
            field=models.CharField(default='', max_length=50, verbose_name='Como será o frete? (Ex:"Frete R$9,90")'),
        ),
        migrations.AddField(
            model_name='planos',
            name='descricao',
            field=models.CharField(default='', max_length=300, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='planos',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome do Plano'),
        ),
        migrations.AddField(
            model_name='planos',
            name='refeicoes',
            field=models.IntegerField(default='', verbose_name='Quantidade de refeições'),
        ),
        migrations.AddField(
            model_name='planos',
            name='subdescricao',
            field=models.CharField(default='', max_length=300, verbose_name='Sub-descrição'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='descricao',
            field=models.TextField(default='', help_text='Escreva aqui', verbose_name='Breve descrição sobre o problema'),
        ),
    ]
