# Generated by Django 3.0.8 on 2020-07-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200721_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='dogEspecial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CachorroEspecial'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='anexo',
            field=models.FileField(blank=True, help_text='Clique ou arraste os arquivos nessa área para anexá-los', null=True, upload_to='uploads/anexos/%Y/%m/', verbose_name='Algum exame ou receita?'),
        ),
    ]
