# Generated by Django 3.0.8 on 2020-07-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200721_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='idCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
    ]
