# Generated by Django 3.0.8 on 2020-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200722_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='calculodia',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Quantidade de ração diária para o cão (g/dia)'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='calculomes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Quantidade de ração a receber (kg/mês)'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome do seu Dog'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='peso',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Observação: Não sabe o peso exato? Não faz mal, você pode inserir um peso próximo.', max_digits=3, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='pesoideal',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Segundo o conselho veterinario, caso seu cão tenha até 12 meses é obrigatorio você informar o peso ideal dele quando adulto. Fique tranquilo, você pode informar o peso aproximado.', max_digits=3, verbose_name='Peso Ideal'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.CharField(default='', max_length=100, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor do pedido'),
        ),
    ]
