# Generated by Django 3.0.8 on 2020-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200722_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='pesoideal',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Segundo o conselho veterinario, caso seu cão tenha até 12 meses é obrigatorio você informar o peso ideal dele quando adulto. Fique tranquilo, você pode informar o peso aproximado.', max_digits=3, null=True, verbose_name='Peso Ideal'),
        ),
    ]
