# Generated by Django 3.0.8 on 2020-07-24 21:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200722_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorroespecial',
            name='condicao',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('alergia', 'Alegia'), ('cardiaco', 'Cardiaco'), ('diabetes', 'Diabetes'), ('renal', 'Renal'), ('obesidade', 'Obesidade'), ('intestinal', 'Instestinal'), ('outro', 'Outro')], max_length=200, null=True, verbose_name='Qual o problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='descricao',
            field=models.TextField(blank=True, default='', help_text='Escreva aqui', null=True, verbose_name='Breve descrição sobre o problema'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='medicamento',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ele toma algum medicamento?'),
        ),
    ]
