# Generated by Django 3.0.8 on 2020-07-25 16:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('app', '0008_auto_20200724_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planos',
            new_name='Plano',
        ),
    ]
