# Generated by Django 3.0.8 on 2020-07-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200725_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='calculodia',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Quantidade de ração diária para o cão (g/dia)'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='calculomes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Quantidade de ração a receber (kg/mês)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idEntrega',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Entrega'),
        ),
    ]
