# Generated by Django 3.0.8 on 2020-07-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200726_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='refDog',
        ),
        migrations.AddField(
            model_name='pedido',
            name='idDog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cachorro'),
        ),
    ]
