# Generated by Django 3.0.8 on 2020-07-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200726_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='preferencia',
            field=models.CharField(choices=[('Portaria', 'Pode deixar na portaria.'), ('Em mãos', 'Sempre em mãos')], default='', max_length=150, verbose_name='Para quem podemos entregar?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pedido em aberto', 'Pedido em aberto'), ('Pedido finalizado pelo cliente', 'Pedido finalizado pelo cliente'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Pedido em preparo', 'Pedido em preparo'), ('Pedido em trânsito', 'Pedido em trânsito'), ('Pedido concluído', 'Pedido concluído')], default='Pedido em aberto', max_length=100, verbose_name='Status do pedido'),
        ),
    ]
