# Generated by Django 3.0.8 on 2020-07-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200727_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='calculodia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Quantidade de ração diária para o cão (g/dia)'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='calculomes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Quantidade de ração a receber (kg/mês)'),
        ),
    ]
