# Generated by Django 3.0.8 on 2020-07-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200727_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plano', models.CharField(blank=True, default='', max_length=200)),
                ('status_adesao', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='idCarrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app.Carrinho'),
        ),
    ]
