# Generated by Django 3.0.8 on 2020-07-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200728_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='areatelefone',
            field=models.BigIntegerField(default=0, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.BigIntegerField(default=0, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
    ]
