# Generated by Django 3.0.8 on 2020-07-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='areatelefone',
            field=models.BigIntegerField(default=0, verbose_name='Código de área'),
        ),
    ]
