# Generated by Django 3.0.8 on 2020-07-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200729_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='pagseguro_plano',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
