# Generated by Django 3.0.8 on 2020-07-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_carrinho_pagseguro_adesao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='areatelefone',
            field=models.BigIntegerField(default=0, verbose_name='DDD'),
        ),
    ]
