# Generated by Django 3.0.8 on 2020-08-02 16:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200801_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorroespecial',
            name='condicao',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('alergia', 'Alergia'), ('cardiaco', 'Cardiaco'), ('diabetes', 'Diabetes'), ('renal', 'Renal'), ('obesidade', 'Obesidade'), ('intestinal', 'Instestinal'), ('outro', 'Outro')], max_length=200, null=True, verbose_name='Qual o problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='frequencia',
            field=models.IntegerField(choices=[('1 Entrega no mês', ' 1 Entrega no mês (Grátis)'), ('2 Entregas no mês', '2 Entregas no mês (R$9,90)')], default=0, verbose_name='Com qual frequência quer receber a Ração do Futuro?'),
        ),
    ]
