# Generated by Django 3.0.8 on 2020-08-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200802_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idDog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='app.Cachorro'),
        ),
    ]
