# Generated by Django 3.0.8 on 2020-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200810_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=13, verbose_name='CPF'),
        ),
    ]
