# Generated by Django 3.0.8 on 2020-08-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200810_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bairro'),
        ),
    ]
