# Generated by Django 3.0.8 on 2020-08-12 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_cliente_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='areatelefone',
            field=models.CharField(max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.BigIntegerField(null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Digite apenas o número do seu telefone', regex='^\\+?1?\\d{8,9}$')], verbose_name='Telefone'),
        ),
    ]
