# Generated by Django 3.1 on 2020-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200812_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachorroespecial',
            name='anexo',
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='castrado',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], default=0, max_length=50, verbose_name='Ele é castrado?'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='fisico',
            field=models.CharField(choices=[('Magro', 'Magro'), ('Na Medida', 'Na Medida'), ('Gordinho', 'Gordinho'), ('Obeso', 'Obeso')], default='', max_length=100, verbose_name='Físico do cão'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Breve descrição sobre o problema'),
        ),
        migrations.AlterField(
            model_name='cachorroespecial',
            name='medicamento',
            field=models.BooleanField(choices=[(1, 'Sim'), (0, 'Não')], default=0, verbose_name='Ele toma algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=60, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=60, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=40, verbose_name='Complemento (opcional)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='', max_length=80, verbose_name='Endereço'),
        ),
    ]
