# Generated by Django 3.1 on 2020-08-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200813_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='dogEspecial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cachorro', to='app.cachorroespecial'),
        ),
    ]
