# Generated by Django 3.1 on 2020-08-18 19:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200818_0021'),
    ]
        migrations.AlterField(
            model_name='entrega',
            name='dia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], default='', max_length=250, verbose_name='Quais dias da semana você pode receber a Ração Do Futuro?'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='preferencia',
            field=models.CharField(choices=[('Portaria', 'Pode deixar na portaria'), ('Em mãos', 'Sempre em mãos')], default='', max_length=150, verbose_name='Para quem podemos entregar?'),
        ),
    ]
