# Generated by Django 3.1 on 2020-08-18 19:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200818_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='sabores',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Carne de panela', 'https://res.cloudinary.com/dr1cvxypv/image/upload/c_scale,w_345/v1597777400/rf/carne_qwjvgl.png'), ('Frango Xadrez', 'https://res.cloudinary.com/dr1cvxypv/image/upload/c_scale,w_345/v1597777400/rf/frango_jucebo.png'), ('Risoto Suíno', 'https://res.cloudinary.com/dr1cvxypv/image/upload/c_scale,w_345/v1597777400/rf/risoto_xf3jqt.png')], default='', max_length=42, verbose_name='Escolha os sabores do futuro'),
        ),
    ]
