# Generated by Django 3.1 on 2020-08-18 19:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200818_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='sabores',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Carne de panela', '/static/css/images/carne.png'), ('Frango Xadrez', '/static/css/images/frango.png'), ('Risoto Suíno', '/static/css/images/risoto.png')], default='', max_length=42, verbose_name='Escolha os sabores do futuro'),
        ),
    ]
