# Generated by Django 3.1 on 2020-08-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200818_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='atividade',
            field=models.CharField(choices=[('Caminhadas Diárias', 'De 30 min até 1:30 de caminhadas diárias.'), ('Super Ativo', '1:30 até 2:30 de caminhadas diárias.'), ('Nivel Olímpico', '2:30 até 3:30 de caminhadas diárias.')], default='', max_length=250, verbose_name='Nivel de atividade Diária'),
        ),
    ]
