# Generated by Django 3.1 on 2020-08-18 21:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200818_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='dia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], default='', max_length=40, verbose_name='Quais dias da semana você pode receber a Ração Do Futuro?'),
        ),
    ]
