# Generated by Django 3.1 on 2020-08-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200819_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], default='', max_length=50, verbose_name='Sexo'),
        ),
    ]
