# Generated by Django 3.1 on 2020-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200819_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Fêmea')], default='', max_length=50, verbose_name='Sexo'),
        ),
    ]
