# Generated by Django 3.1 on 2020-08-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200819_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome do seu dog'),
        ),
    ]
