# Generated by Django 3.1 on 2020-08-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200820_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pedido em aberto', 'Pedido em aberto'), ('Carrinho criado', 'Carrinho criado'), ('Pedido finalizado pelo cliente', 'Pedido finalizado pelo cliente'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Pedido em preparo', 'Pedido em preparo'), ('Pedido em trânsito', 'Pedido em trânsito'), ('Pedido concluído', 'Pedido concluído')], default='Pedido em aberto', max_length=100, verbose_name='Status do pedido'),
        ),
    ]
