# Generated by Django 3.1 on 2020-09-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20200826_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cupom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
