# Generated by Django 3.1 on 2020-09-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_carrinho_cupom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='status_adesao',
        ),
    ]
